import "../styles/global.css";
import Nav from "../components/navigation.jsx";

export const metadata = {
  title: {
    template: "%s | Next js",
    default: "Movie Page",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
